const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const rateLimit = require('express-rate-limit');
const { buildContainer } = require('./container');
const buildAuthRouter = require('../interface/http/routes/auth');
const buildOrdersRouter = require('../interface/http/routes/orders');
const buildWebhooksRouter = require('../interface/http/routes/webhooks');
const buildProtocolsRouter = require('../interface/http/routes/protocols');
const buildSchedulesRouter = require('../interface/http/routes/schedules');
const buildAppointmentsRouter = require('../interface/http/routes/appointments');
const buildHoldsRouter = require('../interface/http/routes/holds');
const buildUsersRouter = require('../interface/http/routes/users');
const buildCertificatesRouter = require('../interface/http/routes/certificates');
const buildIntegrationsRouter = require('../interface/http/routes/integrations');
const container = buildContainer();
const app = express();
app.use(helmet());
app.use(express.json({ limit:'1mb' }));
const allowedOrigin = container.env.frontendOrigin || 'http://localhost:5173';
app.use(cors({ origin: allowedOrigin, credentials: true }));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, max: 1000 }));
app.get('/health', (_req,res)=> res.json({ ok:true }));
app.use('/auth', buildAuthRouter(container));
app.use('/orders', buildOrdersRouter(container));
app.use('/webhooks', buildWebhooksRouter(container));
app.use('/protocols', buildProtocolsRouter());
app.use('/schedules', buildSchedulesRouter(container));
app.use('/appointments', buildAppointmentsRouter(container));
app.use('/holds', buildHoldsRouter(container));
app.use('/users', buildUsersRouter(container));
app.use('/certificates', buildCertificatesRouter(container));
app.use('/integrations', buildIntegrationsRouter());
// Serve admin static
const path = require('path');
const expressStatic = require('express');
const adminDist = path.resolve(__dirname, '../../dist/admin');
app.use('/admin', expressStatic.static(adminDist));
app.get(/^\/admin(?:\/.*)?$/, (_req,res)=>{
  res.sendFile(path.join(adminDist, 'index.html'));
});
const port = container.env.apiPort || 3000;
app.listen(port, ()=> console.log(`[API] http://localhost:${port}`));
